export interface UnicodeChar {
  char: string
  name: string
  code: string
  category: string
  subcategory?: string
}

function ch(char: string, name: string, _aliases: string[], category: string, subcategory: string): UnicodeChar {
  const cp = char.codePointAt(0)!
  return { char, name, code: `U+${cp.toString(16).toUpperCase().padStart(4, '0')}`, category, subcategory }
}

export interface Category {
  id: string
  label: string
}

export const CATEGORIES: Category[] = [
  { id: 'common', label: 'Common' },
  { id: 'currency', label: 'Currency' },
  { id: 'math', label: 'Math' },
  { id: 'arrows', label: 'Arrows' },
  { id: 'greek', label: 'Greek' },
  { id: 'shapes', label: 'Shapes' },
  { id: 'music', label: 'Music' },
  { id: 'box', label: 'Box Drawing' },
  { id: 'latin', label: 'Latin' },
  { id: 'cyrillic', label: 'Cyrillic' },
  { id: 'arabic', label: 'Arabic' },
  { id: 'cjk', label: 'CJK' },
  { id: 'devanagari', label: 'Devanagari' },
  { id: 'hebrew', label: 'Hebrew' },
  { id: 'technical', label: 'Tech' },
  { id: 'emoji', label: 'Emoji' },
]

const ALL: UnicodeChar[] = [
  // ── BASIC PUNCTUATION ──────────────────────────────────────────
  ch('/', 'SOLIDUS', ['slash', 'forward slash', 'divide', 'fraction bar'], 'common', 'basic'),
  ch('\\', 'REVERSE SOLIDUS', ['backslash', 'escape'], 'common', 'basic'),
  ch('-', 'HYPHEN-MINUS', ['hyphen', 'minus', 'dash', 'line'], 'common', 'basic'),
  ch('_', 'LOW LINE', ['underscore', 'underline'], 'common', 'basic'),
  ch('*', 'ASTERISK', ['star', 'asterisk', 'bullet', 'multiply'], 'common', 'basic'),
  ch('+', 'PLUS SIGN', ['plus', 'add', 'positive'], 'common', 'basic'),
  ch('=', 'EQUALS SIGN', ['equals', 'equal', 'same'], 'common', 'basic'),
  ch('~', 'TILDE', ['tilde', 'approx', 'squiggle'], 'common', 'basic'),
  ch('^', 'CIRCUMFLEX ACCENT', ['caret', 'circumflex', 'power'], 'common', 'basic'),
  ch('|', 'VERTICAL LINE', ['pipe', 'bar', 'or'], 'common', 'basic'),
  ch('@', 'COMMERCIAL AT', ['at sign', 'at', 'email'], 'common', 'basic'),
  ch('#', 'NUMBER SIGN', ['hash', 'pound', 'hashtag'], 'common', 'basic'),
  ch('%', 'PERCENT SIGN', ['percent', 'percentage'], 'common', 'basic'),
  ch('&', 'AMPERSAND', ['and', 'ampersand'], 'common', 'basic'),
  ch('<', 'LESS-THAN SIGN', ['less than', 'left angle'], 'common', 'basic'),
  ch('>', 'GREATER-THAN SIGN', ['greater than', 'right angle'], 'common', 'basic'),

  // ── existing entries ───────────────────────────────────────────
  { char: '©', name: 'Copyright', code: 'U+00A9', category: 'common' },
  { char: '®', name: 'Registered', code: 'U+00AE', category: 'common' },
  { char: '™', name: 'Trademark', code: 'U+2122', category: 'common' },
  { char: '§', name: 'Section', code: 'U+00A7', category: 'common' },
  { char: '¶', name: 'Pilcrow', code: 'U+00B6', category: 'common' },
  { char: '†', name: 'Dagger', code: 'U+2020', category: 'common' },
  { char: '‡', name: 'Double Dagger', code: 'U+2021', category: 'common' },
  { char: '•', name: 'Bullet', code: 'U+2022', category: 'common' },
  { char: '✓', name: 'Check Mark', code: 'U+2713', category: 'common' },
  { char: '✔', name: 'Heavy Check Mark', code: 'U+2714', category: 'common' },
  { char: '✕', name: 'Multiplication X', code: 'U+2715', category: 'common' },
  { char: '✗', name: 'Ballot X', code: 'U+2717', category: 'common' },
  { char: '★', name: 'Black Star', code: 'U+2605', category: 'common' },
  { char: '☆', name: 'White Star', code: 'U+2606', category: 'common' },
  { char: '☎', name: 'Black Telephone', code: 'U+260E', category: 'common' },
  { char: '☠', name: 'Skull', code: 'U+2620', category: 'common' },
  { char: '☢', name: 'Radioactive', code: 'U+2622', category: 'common' },
  { char: '☣', name: 'Biohazard', code: 'U+2623', category: 'common' },
  { char: '☤', name: 'Caduceus', code: 'U+2624', category: 'common' },
  { char: '☮', name: 'Peace', code: 'U+262E', category: 'common' },
  { char: '☯', name: 'Yin Yang', code: 'U+262F', category: 'common' },
  { char: '☸', name: 'Wheel of Dharma', code: 'U+2638', category: 'common' },
  { char: '☺', name: 'White Smiling Face', code: 'U+263A', category: 'common' },
  { char: '♻', name: 'Recycling', code: 'U+267B', category: 'common' },
  { char: '⚕', name: 'Medical', code: 'U+2695', category: 'common' },
  { char: '⚙', name: 'Gear', code: 'U+2699', category: 'common' },
  { char: '⚛', name: 'Atom', code: 'U+269B', category: 'common' },
  { char: '⚠', name: 'Warning', code: 'U+26A0', category: 'common' },
  { char: '⚡', name: 'High Voltage', code: 'U+26A1', category: 'common' },
  { char: '⚰', name: 'Coffin', code: 'U+26B0', category: 'common' },
  { char: '⛔', name: 'No Entry', code: 'U+26D4', category: 'common' },
  { char: '✈', name: 'Airplane', code: 'U+2708', category: 'common' },
  { char: '✉', name: 'Envelope', code: 'U+2709', category: 'common' },
  { char: '✌', name: 'Victory Hand', code: 'U+270C', category: 'common' },
  { char: '✏', name: 'Pencil', code: 'U+270F', category: 'common' },
  { char: '⁰', name: 'Superscript 0', code: 'U+2070', category: 'common' },
  { char: '¹', name: 'Superscript 1', code: 'U+00B9', category: 'common' },
  { char: '²', name: 'Superscript 2', code: 'U+00B2', category: 'common' },
  { char: '³', name: 'Superscript 3', code: 'U+00B3', category: 'common' },
  { char: '⁴', name: 'Superscript 4', code: 'U+2074', category: 'common' },
  { char: '⁵', name: 'Superscript 5', code: 'U+2075', category: 'common' },
  { char: '⁶', name: 'Superscript 6', code: 'U+2076', category: 'common' },
  { char: '⁷', name: 'Superscript 7', code: 'U+2077', category: 'common' },
  { char: '⁸', name: 'Superscript 8', code: 'U+2078', category: 'common' },
  { char: '⁹', name: 'Superscript 9', code: 'U+2079', category: 'common' },
  { char: '₀', name: 'Subscript 0', code: 'U+2080', category: 'common' },
  { char: '₁', name: 'Subscript 1', code: 'U+2081', category: 'common' },
  { char: '₂', name: 'Subscript 2', code: 'U+2082', category: 'common' },
  { char: '₃', name: 'Subscript 3', code: 'U+2083', category: 'common' },
  { char: '₄', name: 'Subscript 4', code: 'U+2084', category: 'common' },
  { char: '₅', name: 'Subscript 5', code: 'U+2085', category: 'common' },
  { char: '₆', name: 'Subscript 6', code: 'U+2086', category: 'common' },
  { char: '₇', name: 'Subscript 7', code: 'U+2087', category: 'common' },
  { char: '₈', name: 'Subscript 8', code: 'U+2088', category: 'common' },
  { char: '₉', name: 'Subscript 9', code: 'U+2089', category: 'common' },
  { char: '$', name: 'Dollar', code: 'U+0024', category: 'currency' },
  { char: '¢', name: 'Cent', code: 'U+00A2', category: 'currency' },
  { char: '£', name: 'Pound', code: 'U+00A3', category: 'currency' },
  { char: '¤', name: 'Currency', code: 'U+00A4', category: 'currency' },
  { char: '¥', name: 'Yen', code: 'U+00A5', category: 'currency' },
  { char: '₡', name: 'Colon', code: 'U+20A1', category: 'currency' },
  { char: '₣', name: 'Franc', code: 'U+20A3', category: 'currency' },
  { char: '₤', name: 'Lira', code: 'U+20A4', category: 'currency' },
  { char: '₦', name: 'Naira', code: 'U+20A6', category: 'currency' },
  { char: '₨', name: 'Rupee', code: 'U+20A8', category: 'currency' },
  { char: '₩', name: 'Won', code: 'U+20A9', category: 'currency' },
  { char: '₪', name: 'New Sheqel', code: 'U+20AA', category: 'currency' },
  { char: '₫', name: 'Dong', code: 'U+20AB', category: 'currency' },
  { char: '€', name: 'Euro', code: 'U+20AC', category: 'currency' },
  { char: '₭', name: 'Kip', code: 'U+20AD', category: 'currency' },
  { char: '₮', name: 'Tugrik', code: 'U+20AE', category: 'currency' },
  { char: '₱', name: 'Peso', code: 'U+20B1', category: 'currency' },
  { char: '₲', name: 'Guarani', code: 'U+20B2', category: 'currency' },
  { char: '₴', name: 'Hryvnia', code: 'U+20B4', category: 'currency' },
  { char: '₵', name: 'Cedi', code: 'U+20B5', category: 'currency' },
  { char: '₸', name: 'Tenge', code: 'U+20B8', category: 'currency' },
  { char: '₹', name: 'Indian Rupee', code: 'U+20B9', category: 'currency' },
  { char: '₺', name: 'Turkish Lira', code: 'U+20BA', category: 'currency' },
  { char: '₼', name: 'Manat', code: 'U+20BC', category: 'currency' },
  { char: '₽', name: 'Ruble', code: 'U+20BD', category: 'currency' },
  { char: '₿', name: 'Bitcoin', code: 'U+20BF', category: 'currency' },
  { char: '+', name: 'Plus', code: 'U+002B', category: 'math' },
  { char: '\u2212', name: 'Minus', code: 'U+2212', category: 'math' },
  { char: '±', name: 'Plus-Minus', code: 'U+00B1', category: 'math' },
  { char: '×', name: 'Multiplication', code: 'U+00D7', category: 'math' },
  { char: '÷', name: 'Division', code: 'U+00F7', category: 'math' },
  { char: '=', name: 'Equals', code: 'U+003D', category: 'math' },
  { char: '\u2260', name: 'Not Equal', code: 'U+2260', category: 'math' },
  { char: '\u2248', name: 'Approximately', code: 'U+2248', category: 'math' },
  { char: '\u2245', name: 'Approx Equal', code: 'U+2245', category: 'math' },
  { char: '\u2261', name: 'Identical To', code: 'U+2261', category: 'math' },
  { char: '<', name: 'Less Than', code: 'U+003C', category: 'math' },
  { char: '>', name: 'Greater Than', code: 'U+003E', category: 'math' },
  { char: '\u2264', name: 'Less Than or Equal', code: 'U+2264', category: 'math' },
  { char: '\u2265', name: 'Greater Than or Equal', code: 'U+2265', category: 'math' },
  { char: '\u221E', name: 'Infinity', code: 'U+221E', category: 'math' },
  { char: '\u2202', name: 'Partial Differential', code: 'U+2202', category: 'math' },
  { char: '\u2206', name: 'Increment', code: 'U+2206', category: 'math' },
  { char: '\u2207', name: 'Nabla', code: 'U+2207', category: 'math' },
  { char: '\u221A', name: 'Square Root', code: 'U+221A', category: 'math' },
  { char: '\u221B', name: 'Cube Root', code: 'U+221B', category: 'math' },
  { char: '\u2211', name: 'Summation', code: 'U+2211', category: 'math' },
  { char: '\u220F', name: 'Product', code: 'U+220F', category: 'math' },
  { char: '\u222B', name: 'Integral', code: 'U+222B', category: 'math' },
  { char: '\u222C', name: 'Double Integral', code: 'U+222C', category: 'math' },
  { char: '\u222E', name: 'Contour Integral', code: 'U+222E', category: 'math' },
  { char: '\u2234', name: 'Therefore', code: 'U+2234', category: 'math' },
  { char: '\u2235', name: 'Because', code: 'U+2235', category: 'math' },
  { char: '\u2208', name: 'Element Of', code: 'U+2208', category: 'math' },
  { char: '\u2209', name: 'Not Element Of', code: 'U+2209', category: 'math' },
  { char: '\u220B', name: 'Contains As Member', code: 'U+220B', category: 'math' },
  { char: '\u2220', name: 'Angle', code: 'U+2220', category: 'math' },
  { char: '\u2225', name: 'Parallel To', code: 'U+2225', category: 'math' },
  { char: '\u2227', name: 'Logical And', code: 'U+2227', category: 'math' },
  { char: '\u2228', name: 'Logical Or', code: 'U+2228', category: 'math' },
  { char: '\u2229', name: 'Intersection', code: 'U+2229', category: 'math' },
  { char: '\u222A', name: 'Union', code: 'U+222A', category: 'math' },
  { char: '\u2282', name: 'Subset Of', code: 'U+2282', category: 'math' },
  { char: '\u2283', name: 'Superset Of', code: 'U+2283', category: 'math' },
  { char: '\u2286', name: 'Subset Or Equal', code: 'U+2286', category: 'math' },
  { char: '\u2287', name: 'Superset Or Equal', code: 'U+2287', category: 'math' },
  { char: '\u2295', name: 'Circled Plus', code: 'U+2295', category: 'math' },
  { char: '\u2297', name: 'Circled Times', code: 'U+2297', category: 'math' },
  { char: '\u2299', name: 'Circled Dot', code: 'U+2299', category: 'math' },
  { char: '\u22A5', name: 'Up Tack', code: 'U+22A5', category: 'math' },
  { char: '\u2200', name: 'For All', code: 'U+2200', category: 'math' },
  { char: '\u2203', name: 'There Exists', code: 'U+2203', category: 'math' },
  { char: '\u2205', name: 'Empty Set', code: 'U+2205', category: 'math' },
  { char: '\u2115', name: 'Natural Numbers', code: 'U+2115', category: 'math' },
  { char: '\u2124', name: 'Integers', code: 'U+2124', category: 'math' },
  { char: '\u211A', name: 'Rational Numbers', code: 'U+211A', category: 'math' },
  { char: '\u211D', name: 'Real Numbers', code: 'U+211D', category: 'math' },
  { char: '\u2102', name: 'Complex Numbers', code: 'U+2102', category: 'math' },
  { char: '\u210D', name: 'Quaternions', code: 'U+210D', category: 'math' },
  { char: '\u2119', name: 'Prime Numbers', code: 'U+2119', category: 'math' },
  { char: '\u00B0', name: 'Degree', code: 'U+00B0', category: 'math' },
  { char: '\u2032', name: 'Prime', code: 'U+2032', category: 'math' },
  { char: '\u2033', name: 'Double Prime', code: 'U+2033', category: 'math' },
  { char: '\u00B5', name: 'Micro Sign', code: 'U+00B5', category: 'math' },
  { char: '\u03C0', name: 'Pi', code: 'U+03C0', category: 'math' },
  { char: '\u2113', name: 'Script Small L', code: 'U+2113', category: 'math' },
  { char: '\u2135', name: 'Alef Symbol', code: 'U+2135', category: 'math' },
  { char: '\u0192', name: 'Function (florin)', code: 'U+0192', category: 'math' },
  { char: '\u2190', name: 'Leftwards Arrow', code: 'U+2190', category: 'arrows' },
  { char: '\u2191', name: 'Upwards Arrow', code: 'U+2191', category: 'arrows' },
  { char: '\u2192', name: 'Rightwards Arrow', code: 'U+2192', category: 'arrows' },
  { char: '\u2193', name: 'Downwards Arrow', code: 'U+2193', category: 'arrows' },
  { char: '\u2194', name: 'Left Right Arrow', code: 'U+2194', category: 'arrows' },
  { char: '\u2195', name: 'Up Down Arrow', code: 'U+2195', category: 'arrows' },
  { char: '\u2196', name: 'North West Arrow', code: 'U+2196', category: 'arrows' },
  { char: '\u2197', name: 'North East Arrow', code: 'U+2197', category: 'arrows' },
  { char: '\u2198', name: 'South East Arrow', code: 'U+2198', category: 'arrows' },
  { char: '\u2199', name: 'South West Arrow', code: 'U+2199', category: 'arrows' },
  { char: '\u21A9', name: 'Leftwards Arrow with Hook', code: 'U+21A9', category: 'arrows' },
  { char: '\u21AA', name: 'Rightwards Arrow with Hook', code: 'U+21AA', category: 'arrows' },
  { char: '\u21B5', name: 'Downwards Arrow with Corner (Return)', code: 'U+21B5', category: 'arrows' },
  { char: '\u21BA', name: 'Anti-Clockwise Open Circle Arrow', code: 'U+21BA', category: 'arrows' },
  { char: '\u21BB', name: 'Clockwise Open Circle Arrow', code: 'U+21BB', category: 'arrows' },
  { char: '\u21D0', name: 'Leftwards Double Arrow', code: 'U+21D0', category: 'arrows' },
  { char: '\u21D1', name: 'Upwards Double Arrow', code: 'U+21D1', category: 'arrows' },
  { char: '\u21D2', name: 'Rightwards Double Arrow', code: 'U+21D2', category: 'arrows' },
  { char: '\u21D3', name: 'Downwards Double Arrow', code: 'U+21D3', category: 'arrows' },
  { char: '\u21D4', name: 'Left Right Double Arrow', code: 'U+21D4', category: 'arrows' },
]

const ALL2: UnicodeChar[] = [
  { char: '\u21D5', name: 'Up Down Double Arrow', code: 'U+21D5', category: 'arrows' },
  { char: '\u0391', name: 'Alpha (Upper)', code: 'U+0391', category: 'greek' },
  { char: '\u0392', name: 'Beta (Upper)', code: 'U+0392', category: 'greek' },
  { char: '\u0393', name: 'Gamma (Upper)', code: 'U+0393', category: 'greek' },
  { char: '\u0394', name: 'Delta (Upper)', code: 'U+0394', category: 'greek' },
  { char: '\u0395', name: 'Epsilon (Upper)', code: 'U+0395', category: 'greek' },
  { char: '\u0396', name: 'Zeta (Upper)', code: 'U+0396', category: 'greek' },
  { char: '\u0397', name: 'Eta (Upper)', code: 'U+0397', category: 'greek' },
  { char: '\u0398', name: 'Theta (Upper)', code: 'U+0398', category: 'greek' },
  { char: '\u0399', name: 'Iota (Upper)', code: 'U+0399', category: 'greek' },
  { char: '\u039A', name: 'Kappa (Upper)', code: 'U+039A', category: 'greek' },
  { char: '\u039B', name: 'Lambda (Upper)', code: 'U+039B', category: 'greek' },
  { char: '\u039C', name: 'Mu (Upper)', code: 'U+039C', category: 'greek' },
  { char: '\u039D', name: 'Nu (Upper)', code: 'U+039D', category: 'greek' },
  { char: '\u039E', name: 'Xi (Upper)', code: 'U+039E', category: 'greek' },
  { char: '\u039F', name: 'Omicron (Upper)', code: 'U+039F', category: 'greek' },
  { char: '\u03A0', name: 'Pi (Upper)', code: 'U+03A0', category: 'greek' },
  { char: '\u03A1', name: 'Rho (Upper)', code: 'U+03A1', category: 'greek' },
  { char: '\u03A3', name: 'Sigma (Upper)', code: 'U+03A3', category: 'greek' },
  { char: '\u03A4', name: 'Tau (Upper)', code: 'U+03A4', category: 'greek' },
  { char: '\u03A5', name: 'Upsilon (Upper)', code: 'U+03A5', category: 'greek' },
  { char: '\u03A6', name: 'Phi (Upper)', code: 'U+03A6', category: 'greek' },
  { char: '\u03A7', name: 'Chi (Upper)', code: 'U+03A7', category: 'greek' },
  { char: '\u03A8', name: 'Psi (Upper)', code: 'U+03A8', category: 'greek' },
  { char: '\u03A9', name: 'Omega (Upper)', code: 'U+03A9', category: 'greek' },
  { char: '\u03B1', name: 'Alpha (Lower)', code: 'U+03B1', category: 'greek' },
  { char: '\u03B2', name: 'Beta (Lower)', code: 'U+03B2', category: 'greek' },
  { char: '\u03B3', name: 'Gamma (Lower)', code: 'U+03B3', category: 'greek' },
  { char: '\u03B4', name: 'Delta (Lower)', code: 'U+03B4', category: 'greek' },
  { char: '\u03B5', name: 'Epsilon (Lower)', code: 'U+03B5', category: 'greek' },
  { char: '\u03B6', name: 'Zeta (Lower)', code: 'U+03B6', category: 'greek' },
  { char: '\u03B7', name: 'Eta (Lower)', code: 'U+03B7', category: 'greek' },
  { char: '\u03B8', name: 'Theta (Lower)', code: 'U+03B8', category: 'greek' },
  { char: '\u03B9', name: 'Iota (Lower)', code: 'U+03B9', category: 'greek' },
  { char: '\u03BA', name: 'Kappa (Lower)', code: 'U+03BA', category: 'greek' },
  { char: '\u03BB', name: 'Lambda (Lower)', code: 'U+03BB', category: 'greek' },
  { char: '\u03BC', name: 'Mu (Lower)', code: 'U+03BC', category: 'greek' },
  { char: '\u03BD', name: 'Nu (Lower)', code: 'U+03BD', category: 'greek' },
  { char: '\u03BE', name: 'Xi (Lower)', code: 'U+03BE', category: 'greek' },
  { char: '\u03BF', name: 'Omicron (Lower)', code: 'U+03BF', category: 'greek' },
  { char: '\u03C0', name: 'Pi (Lower)', code: 'U+03C0', category: 'greek' },
  { char: '\u03C1', name: 'Rho (Lower)', code: 'U+03C1', category: 'greek' },
  { char: '\u03C3', name: 'Sigma (Lower)', code: 'U+03C3', category: 'greek' },
  { char: '\u03C4', name: 'Tau (Lower)', code: 'U+03C4', category: 'greek' },
  { char: '\u03C5', name: 'Upsilon (Lower)', code: 'U+03C5', category: 'greek' },
  { char: '\u03C6', name: 'Phi (Lower)', code: 'U+03C6', category: 'greek' },
  { char: '\u03C7', name: 'Chi (Lower)', code: 'U+03C7', category: 'greek' },
  { char: '\u03C8', name: 'Psi (Lower)', code: 'U+03C8', category: 'greek' },
  { char: '\u03C9', name: 'Omega (Lower)', code: 'U+03C9', category: 'greek' },
  { char: '\u03D1', name: 'Theta Symbol', code: 'U+03D1', category: 'greek' },
  { char: '\u03D5', name: 'Phi Symbol', code: 'U+03D5', category: 'greek' },
  { char: '\u03D6', name: 'Pi Symbol', code: 'U+03D6', category: 'greek' },
  { char: '\u03F0', name: 'Kappa Symbol', code: 'U+03F0', category: 'greek' },
  { char: '\u03F1', name: 'Rho Symbol', code: 'U+03F1', category: 'greek' },
  { char: '\u25A0', name: 'Black Square', code: 'U+25A0', category: 'shapes' },
  { char: '\u25A1', name: 'White Square', code: 'U+25A1', category: 'shapes' },
  { char: '\u25AA', name: 'Black Small Square', code: 'U+25AA', category: 'shapes' },
  { char: '\u25AB', name: 'White Small Square', code: 'U+25AB', category: 'shapes' },
  { char: '\u25B2', name: 'Black Up-Pointing Triangle', code: 'U+25B2', category: 'shapes' },
  { char: '\u25B3', name: 'White Up-Pointing Triangle', code: 'U+25B3', category: 'shapes' },
  { char: '\u25B6', name: 'Black Right-Pointing Triangle', code: 'U+25B6', category: 'shapes' },
  { char: '\u25B7', name: 'White Right-Pointing Triangle', code: 'U+25B7', category: 'shapes' },
  { char: '\u25BC', name: 'Black Down-Pointing Triangle', code: 'U+25BC', category: 'shapes' },
  { char: '\u25BD', name: 'White Down-Pointing Triangle', code: 'U+25BD', category: 'shapes' },
  { char: '\u25C0', name: 'Black Left-Pointing Triangle', code: 'U+25C0', category: 'shapes' },
  { char: '\u25C1', name: 'White Left-Pointing Triangle', code: 'U+25C1', category: 'shapes' },
  { char: '\u25C6', name: 'Black Diamond', code: 'U+25C6', category: 'shapes' },
  { char: '\u25C7', name: 'White Diamond', code: 'U+25C7', category: 'shapes' },
  { char: '\u25CA', name: 'Lozenge', code: 'U+25CA', category: 'shapes' },
  { char: '\u25CB', name: 'White Circle', code: 'U+25CB', category: 'shapes' },
  { char: '\u25CF', name: 'Black Circle', code: 'U+25CF', category: 'shapes' },
  { char: '\u25E6', name: 'White Bullet', code: 'U+25E6', category: 'shapes' },
  { char: '\u25EF', name: 'Large Circle', code: 'U+25EF', category: 'shapes' },
  { char: '\u25FB', name: 'White Medium Square', code: 'U+25FB', category: 'shapes' },
  { char: '\u25FC', name: 'Black Medium Square', code: 'U+25FC', category: 'shapes' },
  { char: '\u25FD', name: 'White Medium Small Square', code: 'U+25FD', category: 'shapes' },
  { char: '\u25FE', name: 'Black Medium Small Square', code: 'U+25FE', category: 'shapes' },
  { char: '\u2669', name: 'Quarter Note', code: 'U+2669', category: 'music' },
  { char: '\u266A', name: 'Eighth Note', code: 'U+266A', category: 'music' },
  { char: '\u266B', name: 'Beamed Eighth Notes', code: 'U+266B', category: 'music' },
  { char: '\u266C', name: 'Beamed Sixteenth Notes', code: 'U+266C', category: 'music' },
  { char: '\u266D', name: 'Flat', code: 'U+266D', category: 'music' },
  { char: '\u266E', name: 'Natural', code: 'U+266E', category: 'music' },
  { char: '\u266F', name: 'Sharp', code: 'U+266F', category: 'music' },
  { char: '\uD834\uDD1E', name: 'G Clef', code: 'U+1D11E', category: 'music' },
  { char: '\u2500', name: 'Light Horizontal', code: 'U+2500', category: 'box' },
  { char: '\u2501', name: 'Heavy Horizontal', code: 'U+2501', category: 'box' },
  { char: '\u2502', name: 'Light Vertical', code: 'U+2502', category: 'box' },
  { char: '\u2503', name: 'Heavy Vertical', code: 'U+2503', category: 'box' },
  { char: '\u250C', name: 'Light Down and Right', code: 'U+250C', category: 'box' },
  { char: '\u2510', name: 'Light Down and Left', code: 'U+2510', category: 'box' },
  { char: '\u2514', name: 'Light Up and Right', code: 'U+2514', category: 'box' },
  { char: '\u2518', name: 'Light Up and Left', code: 'U+2518', category: 'box' },
  { char: '\u251C', name: 'Light Vertical and Right', code: 'U+251C', category: 'box' },
  { char: '\u2524', name: 'Light Vertical and Left', code: 'U+2524', category: 'box' },
  { char: '\u252C', name: 'Light Down and Horizontal', code: 'U+252C', category: 'box' },
  { char: '\u2534', name: 'Light Up and Horizontal', code: 'U+2534', category: 'box' },
  { char: '\u253C', name: 'Light Vertical and Horizontal', code: 'U+253C', category: 'box' },
  { char: '\u2550', name: 'Double Horizontal', code: 'U+2550', category: 'box' },
  { char: '\u2551', name: 'Double Vertical', code: 'U+2551', category: 'box' },
  { char: '\u2554', name: 'Double Down and Right', code: 'U+2554', category: 'box' },
  { char: '\u2557', name: 'Double Down and Left', code: 'U+2557', category: 'box' },
  { char: '\u255A', name: 'Double Up and Right', code: 'U+255A', category: 'box' },
  { char: '\u255D', name: 'Double Up and Left', code: 'U+255D', category: 'box' },
  { char: '\u2560', name: 'Double Vertical and Right', code: 'U+2560', category: 'box' },
  { char: '\u2563', name: 'Double Vertical and Left', code: 'U+2563', category: 'box' },
  { char: '\u2566', name: 'Double Down and Horizontal', code: 'U+2566', category: 'box' },
  { char: '\u2569', name: 'Double Up and Horizontal', code: 'U+2569', category: 'box' },
  { char: '\u256C', name: 'Double Vertical and Horizontal', code: 'U+256C', category: 'box' },
  { char: '\u00C6', name: 'AE (Upper)', code: 'U+00C6', category: 'latin' },
  { char: '\u00E6', name: 'ae (Lower)', code: 'U+00E6', category: 'latin' },
  { char: '\u0152', name: 'OE (Upper)', code: 'U+0152', category: 'latin' },
  { char: '\u0153', name: 'oe (Lower)', code: 'U+0153', category: 'latin' },
  { char: '\u00DF', name: 'Sharp S (eszett)', code: 'U+00DF', category: 'latin' },
  { char: '\u00C0', name: 'A Grave (Upper)', code: 'U+00C0', category: 'latin' },
  { char: '\u00C1', name: 'A Acute (Upper)', code: 'U+00C1', category: 'latin' },
  { char: '\u00C2', name: 'A Circumflex (Upper)', code: 'U+00C2', category: 'latin' },
  { char: '\u00C3', name: 'A Tilde (Upper)', code: 'U+00C3', category: 'latin' },
  { char: '\u00C4', name: 'A Diaeresis (Upper)', code: 'U+00C4', category: 'latin' },
  { char: '\u00C5', name: 'A Ring (Upper)', code: 'U+00C5', category: 'latin' },
  { char: '\u00E0', name: 'a Grave (Lower)', code: 'U+00E0', category: 'latin' },
  { char: '\u00E1', name: 'a Acute (Lower)', code: 'U+00E1', category: 'latin' },
  { char: '\u00E2', name: 'a Circumflex (Lower)', code: 'U+00E2', category: 'latin' },
  { char: '\u00E3', name: 'a Tilde (Lower)', code: 'U+00E3', category: 'latin' },
  { char: '\u00E4', name: 'a Diaeresis (Lower)', code: 'U+00E4', category: 'latin' },
  { char: '\u00E5', name: 'a Ring (Lower)', code: 'U+00E5', category: 'latin' },
  { char: '\u00C8', name: 'E Grave (Upper)', code: 'U+00C8', category: 'latin' },
  { char: '\u00C9', name: 'E Acute (Upper)', code: 'U+00C9', category: 'latin' },
  { char: '\u00CA', name: 'E Circumflex (Upper)', code: 'U+00CA', category: 'latin' },
  { char: '\u00CB', name: 'E Diaeresis (Upper)', code: 'U+00CB', category: 'latin' },
  { char: '\u00E8', name: 'e Grave (Lower)', code: 'U+00E8', category: 'latin' },
  { char: '\u00E9', name: 'e Acute (Lower)', code: 'U+00E9', category: 'latin' },
  { char: '\u00EA', name: 'e Circumflex (Lower)', code: 'U+00EA', category: 'latin' },
  { char: '\u00EB', name: 'e Diaeresis (Lower)', code: 'U+00EB', category: 'latin' },
  { char: '\u00CC', name: 'I Grave (Upper)', code: 'U+00CC', category: 'latin' },
  { char: '\u00CD', name: 'I Acute (Upper)', code: 'U+00CD', category: 'latin' },
  { char: '\u00CE', name: 'I Circumflex (Upper)', code: 'U+00CE', category: 'latin' },
  { char: '\u00CF', name: 'I Diaeresis (Upper)', code: 'U+00CF', category: 'latin' },
  { char: '\u00EC', name: 'i Grave (Lower)', code: 'U+00EC', category: 'latin' },
  { char: '\u00ED', name: 'i Acute (Lower)', code: 'U+00ED', category: 'latin' },
  { char: '\u00EE', name: 'i Circumflex (Lower)', code: 'U+00EE', category: 'latin' },
  { char: '\u00EF', name: 'i Diaeresis (Lower)', code: 'U+00EF', category: 'latin' },
  { char: '\u00D2', name: 'O Grave (Upper)', code: 'U+00D2', category: 'latin' },
  { char: '\u00D3', name: 'O Acute (Upper)', code: 'U+00D3', category: 'latin' },
  { char: '\u00D4', name: 'O Circumflex (Upper)', code: 'U+00D4', category: 'latin' },
  { char: '\u00D5', name: 'O Tilde (Upper)', code: 'U+00D5', category: 'latin' },
  { char: '\u00D6', name: 'O Diaeresis (Upper)', code: 'U+00D6', category: 'latin' },
  { char: '\u00F2', name: 'o Grave (Lower)', code: 'U+00F2', category: 'latin' },
  { char: '\u00F3', name: 'o Acute (Lower)', code: 'U+00F3', category: 'latin' },
  { char: '\u00F4', name: 'o Circumflex (Lower)', code: 'U+00F4', category: 'latin' },
  { char: '\u00F5', name: 'o Tilde (Lower)', code: 'U+00F5', category: 'latin' },
  { char: '\u00F6', name: 'o Diaeresis (Lower)', code: 'U+00F6', category: 'latin' },
  { char: '\u00D9', name: 'U Grave (Upper)', code: 'U+00D9', category: 'latin' },
  { char: '\u00DA', name: 'U Acute (Upper)', code: 'U+00DA', category: 'latin' },
  { char: '\u00DB', name: 'U Circumflex (Upper)', code: 'U+00DB', category: 'latin' },
  { char: '\u00DC', name: 'U Diaeresis (Upper)', code: 'U+00DC', category: 'latin' },
  { char: '\u00F9', name: 'u Grave (Lower)', code: 'U+00F9', category: 'latin' },
  { char: '\u00FA', name: 'u Acute (Lower)', code: 'U+00FA', category: 'latin' },
  { char: '\u00FB', name: 'u Circumflex (Lower)', code: 'U+00FB', category: 'latin' },
  { char: '\u00FC', name: 'u Diaeresis (Lower)', code: 'U+00FC', category: 'latin' },
  { char: '\u00DD', name: 'Y Acute (Upper)', code: 'U+00DD', category: 'latin' },
  { char: '\u00FD', name: 'y Acute (Lower)', code: 'U+00FD', category: 'latin' },
  { char: '\u00FE', name: 'Thorn (Lower)', code: 'U+00FE', category: 'latin' },
  { char: '\u00DE', name: 'Thorn (Upper)', code: 'U+00DE', category: 'latin' },
  { char: '\u00D0', name: 'Eth (Upper)', code: 'U+00D0', category: 'latin' },
  { char: '\u00F0', name: 'Eth (Lower)', code: 'U+00F0', category: 'latin' },
  { char: '\u00D1', name: 'N Tilde (Upper)', code: 'U+00D1', category: 'latin' },
  { char: '\u00F1', name: 'n Tilde (Lower)', code: 'U+00F1', category: 'latin' },
  { char: '\u00C7', name: 'C Cedilla (Upper)', code: 'U+00C7', category: 'latin' },
  { char: '\u00E7', name: 'c Cedilla (Lower)', code: 'U+00E7', category: 'latin' },
  { char: '\u011E', name: 'G Breve (Upper)', code: 'U+011E', category: 'latin' },
  { char: '\u011F', name: 'g Breve (Lower)', code: 'U+011F', category: 'latin' },
  { char: '\u0130', name: 'I Dot (Upper)', code: 'U+0130', category: 'latin' },
  { char: '\u0131', name: 'Dotless i (Lower)', code: 'U+0131', category: 'latin' },
  { char: '\u0160', name: 'S Caron (Upper)', code: 'U+0160', category: 'latin' },
  { char: '\u0161', name: 's Caron (Lower)', code: 'U+0161', category: 'latin' },
  { char: '\u017D', name: 'Z Caron (Upper)', code: 'U+017D', category: 'latin' },
  { char: '\u017E', name: 'z Caron (Lower)', code: 'U+017E', category: 'latin' },
  { char: '\u0110', name: 'D Stroke (Upper)', code: 'U+0110', category: 'latin' },
  { char: '\u0111', name: 'd Stroke (Lower)', code: 'U+0111', category: 'latin' },
  { char: '\u00D8', name: 'O Stroke (Upper)', code: 'U+00D8', category: 'latin' },
  { char: '\u00F8', name: 'o Stroke (Lower)', code: 'U+00F8', category: 'latin' },
  { char: '\u0141', name: 'L Stroke (Upper)', code: 'U+0141', category: 'latin' },
  { char: '\u0142', name: 'l Stroke (Lower)', code: 'U+0142', category: 'latin' },
  { char: '\u00BF', name: 'Inverted Question Mark', code: 'U+00BF', category: 'latin' },
  { char: '\u00A1', name: 'Inverted Exclamation Mark', code: 'U+00A1', category: 'latin' },
  { char: '\u00AA', name: 'Feminine Ordinal', code: 'U+00AA', category: 'latin' },
  { char: '\u00BA', name: 'Masculine Ordinal', code: 'U+00BA', category: 'latin' },
  { char: '\u0410', name: 'A (Upper)', code: 'U+0410', category: 'cyrillic' },
  { char: '\u0411', name: 'Be (Upper)', code: 'U+0411', category: 'cyrillic' },
  { char: '\u0412', name: 'Ve (Upper)', code: 'U+0412', category: 'cyrillic' },
  { char: '\u0413', name: 'Ghe (Upper)', code: 'U+0413', category: 'cyrillic' },
  { char: '\u0414', name: 'De (Upper)', code: 'U+0414', category: 'cyrillic' },
  { char: '\u0415', name: 'Ye (Upper)', code: 'U+0415', category: 'cyrillic' },
  { char: '\u0401', name: 'Yo (Upper)', code: 'U+0401', category: 'cyrillic' },
  { char: '\u0416', name: 'Zhe (Upper)', code: 'U+0416', category: 'cyrillic' },
  { char: '\u0417', name: 'Ze (Upper)', code: 'U+0417', category: 'cyrillic' },
  { char: '\u0418', name: 'I (Upper)', code: 'U+0418', category: 'cyrillic' },
  { char: '\u0419', name: 'Short I (Upper)', code: 'U+0419', category: 'cyrillic' },
  { char: '\u041A', name: 'Ka (Upper)', code: 'U+041A', category: 'cyrillic' },
  { char: '\u041B', name: 'El (Upper)', code: 'U+041B', category: 'cyrillic' },
  { char: '\u041C', name: 'Em (Upper)', code: 'U+041C', category: 'cyrillic' },
  { char: '\u041D', name: 'En (Upper)', code: 'U+041D', category: 'cyrillic' },
  { char: '\u041E', name: 'O (Upper)', code: 'U+041E', category: 'cyrillic' },
  { char: '\u041F', name: 'Pe (Upper)', code: 'U+041F', category: 'cyrillic' },
  { char: '\u0420', name: 'Er (Upper)', code: 'U+0420', category: 'cyrillic' },
  { char: '\u0421', name: 'Es (Upper)', code: 'U+0421', category: 'cyrillic' },
  { char: '\u0422', name: 'Te (Upper)', code: 'U+0422', category: 'cyrillic' },
  { char: '\u0423', name: 'U (Upper)', code: 'U+0423', category: 'cyrillic' },
  { char: '\u0424', name: 'Ef (Upper)', code: 'U+0424', category: 'cyrillic' },
  { char: '\u0425', name: 'Kha (Upper)', code: 'U+0425', category: 'cyrillic' },
  { char: '\u0426', name: 'Tse (Upper)', code: 'U+0426', category: 'cyrillic' },
  { char: '\u0427', name: 'Che (Upper)', code: 'U+0427', category: 'cyrillic' },
  { char: '\u0428', name: 'Sha (Upper)', code: 'U+0428', category: 'cyrillic' },
  { char: '\u0429', name: 'Shcha (Upper)', code: 'U+0429', category: 'cyrillic' },
  { char: '\u042A', name: 'Hard Sign (Upper)', code: 'U+042A', category: 'cyrillic' },
  { char: '\u042B', name: 'Yeru (Upper)', code: 'U+042B', category: 'cyrillic' },
  { char: '\u042C', name: 'Soft Sign (Upper)', code: 'U+042C', category: 'cyrillic' },
  { char: '\u042D', name: 'E (Upper)', code: 'U+042D', category: 'cyrillic' },
  { char: '\u042E', name: 'Yu (Upper)', code: 'U+042E', category: 'cyrillic' },
  { char: '\u042F', name: 'Ya (Upper)', code: 'U+042F', category: 'cyrillic' },
  { char: '\u0430', name: 'a (Lower)', code: 'U+0430', category: 'cyrillic' },
  { char: '\u0431', name: 'be (Lower)', code: 'U+0431', category: 'cyrillic' },
  { char: '\u0432', name: 've (Lower)', code: 'U+0432', category: 'cyrillic' },
  { char: '\u0433', name: 'ghe (Lower)', code: 'U+0433', category: 'cyrillic' },
  { char: '\u0434', name: 'de (Lower)', code: 'U+0434', category: 'cyrillic' },
  { char: '\u0435', name: 'ye (Lower)', code: 'U+0435', category: 'cyrillic' },
  { char: '\u0451', name: 'yo (Lower)', code: 'U+0451', category: 'cyrillic' },
  { char: '\u0436', name: 'zhe (Lower)', code: 'U+0436', category: 'cyrillic' },
  { char: '\u0437', name: 'ze (Lower)', code: 'U+0437', category: 'cyrillic' },
  { char: '\u0438', name: 'i (Lower)', code: 'U+0438', category: 'cyrillic' },
  { char: '\u0439', name: 'short i (Lower)', code: 'U+0439', category: 'cyrillic' },
  { char: '\u043A', name: 'ka (Lower)', code: 'U+043A', category: 'cyrillic' },
  { char: '\u043B', name: 'el (Lower)', code: 'U+043B', category: 'cyrillic' },
  { char: '\u043C', name: 'em (Lower)', code: 'U+043C', category: 'cyrillic' },
  { char: '\u043D', name: 'en (Lower)', code: 'U+043D', category: 'cyrillic' },
  { char: '\u043E', name: 'o (Lower)', code: 'U+043E', category: 'cyrillic' },
  { char: '\u043F', name: 'pe (Lower)', code: 'U+043F', category: 'cyrillic' },
  { char: '\u0440', name: 'er (Lower)', code: 'U+0440', category: 'cyrillic' },
  { char: '\u0441', name: 'es (Lower)', code: 'U+0441', category: 'cyrillic' },
  { char: '\u0442', name: 'te (Lower)', code: 'U+0442', category: 'cyrillic' },
  { char: '\u0443', name: 'u (Lower)', code: 'U+0443', category: 'cyrillic' },
  { char: '\u0444', name: 'ef (Lower)', code: 'U+0444', category: 'cyrillic' },
  { char: '\u0445', name: 'kha (Lower)', code: 'U+0445', category: 'cyrillic' },
  { char: '\u0446', name: 'tse (Lower)', code: 'U+0446', category: 'cyrillic' },
  { char: '\u0447', name: 'che (Lower)', code: 'U+0447', category: 'cyrillic' },
  { char: '\u0448', name: 'sha (Lower)', code: 'U+0448', category: 'cyrillic' },
  { char: '\u0449', name: 'shcha (Lower)', code: 'U+0449', category: 'cyrillic' },
  { char: '\u044A', name: 'hard sign (Lower)', code: 'U+044A', category: 'cyrillic' },
  { char: '\u044B', name: 'yeru (Lower)', code: 'U+044B', category: 'cyrillic' },
  { char: '\u044C', name: 'soft sign (Lower)', code: 'U+044C', category: 'cyrillic' },
  { char: '\u044D', name: 'e (Lower)', code: 'U+044D', category: 'cyrillic' },
  { char: '\u044E', name: 'yu (Lower)', code: 'U+044E', category: 'cyrillic' },
  { char: '\u044F', name: 'ya (Lower)', code: 'U+044F', category: 'cyrillic' },
  { char: '\u0627', name: 'Alef', code: 'U+0627', category: 'arabic' },
  { char: '\u0628', name: 'Ba', code: 'U+0628', category: 'arabic' },
  { char: '\u062A', name: 'Ta', code: 'U+062A', category: 'arabic' },
  { char: '\u062B', name: 'Tha', code: 'U+062B', category: 'arabic' },
  { char: '\u062C', name: 'Jim', code: 'U+062C', category: 'arabic' },
  { char: '\u062D', name: 'Ha', code: 'U+062D', category: 'arabic' },
  { char: '\u062E', name: 'Kha', code: 'U+062E', category: 'arabic' },
  { char: '\u062F', name: 'Dal', code: 'U+062F', category: 'arabic' },
  { char: '\u0630', name: 'Dhal', code: 'U+0630', category: 'arabic' },
  { char: '\u0631', name: 'Ra', code: 'U+0631', category: 'arabic' },
  { char: '\u0632', name: 'Zay', code: 'U+0632', category: 'arabic' },
  { char: '\u0633', name: 'Sin', code: 'U+0633', category: 'arabic' },
  { char: '\u0634', name: 'Shin', code: 'U+0634', category: 'arabic' },
  { char: '\u0635', name: 'Sad', code: 'U+0635', category: 'arabic' },
  { char: '\u0636', name: 'Dad', code: 'U+0636', category: 'arabic' },
  { char: '\u0637', name: 'Ta', code: 'U+0637', category: 'arabic' },
  { char: '\u0638', name: 'Za', code: 'U+0638', category: 'arabic' },
  { char: '\u0639', name: 'Ayn', code: 'U+0639', category: 'arabic' },
  { char: '\u063A', name: 'Ghayn', code: 'U+063A', category: 'arabic' },
  { char: '\u0641', name: 'Fa', code: 'U+0641', category: 'arabic' },
  { char: '\u0642', name: 'Qaf', code: 'U+0642', category: 'arabic' },
  { char: '\u0643', name: 'Kaf', code: 'U+0643', category: 'arabic' },
  { char: '\u0644', name: 'Lam', code: 'U+0644', category: 'arabic' },
  { char: '\u0645', name: 'Mim', code: 'U+0645', category: 'arabic' },
  { char: '\u0646', name: 'Nun', code: 'U+0646', category: 'arabic' },
  { char: '\u0647', name: 'Ha', code: 'U+0647', category: 'arabic' },
  { char: '\u0648', name: 'Waw', code: 'U+0648', category: 'arabic' },
  { char: '\u064A', name: 'Ya', code: 'U+064A', category: 'arabic' },
  { char: '\u0660', name: '0 (Indic)', code: 'U+0660', category: 'arabic' },
  { char: '\u0661', name: '1 (Indic)', code: 'U+0661', category: 'arabic' },
  { char: '\u0662', name: '2 (Indic)', code: 'U+0662', category: 'arabic' },
  { char: '\u0663', name: '3 (Indic)', code: 'U+0663', category: 'arabic' },
  { char: '\u0664', name: '4 (Indic)', code: 'U+0664', category: 'arabic' },
  { char: '\u0665', name: '5 (Indic)', code: 'U+0665', category: 'arabic' },
  { char: '\u0666', name: '6 (Indic)', code: 'U+0666', category: 'arabic' },
  { char: '\u0667', name: '7 (Indic)', code: 'U+0667', category: 'arabic' },
  { char: '\u0668', name: '8 (Indic)', code: 'U+0668', category: 'arabic' },
  { char: '\u0669', name: '9 (Indic)', code: 'U+0669', category: 'arabic' },
  { char: '\u2026', name: 'Horizontal Ellipsis', code: 'U+2026', category: 'cjk' },
  { char: '\u3001', name: 'Ideographic Comma', code: 'U+3001', category: 'cjk' },
  { char: '\u3002', name: 'Ideographic Full Stop', code: 'U+3002', category: 'cjk' },
  { char: '\u3005', name: 'Iteration Mark', code: 'U+3005', category: 'cjk' },
  { char: '\u3007', name: 'Number Zero', code: 'U+3007', category: 'cjk' },
  { char: '\u30FB', name: 'Katakana Middle Dot', code: 'U+30FB', category: 'cjk' },
  { char: '\u30FC', name: 'Prolonged Sound Mark', code: 'U+30FC', category: 'cjk' },
  { char: '\u3042', name: 'A (Hiragana)', code: 'U+3042', category: 'cjk' },
  { char: '\u3044', name: 'I (Hiragana)', code: 'U+3044', category: 'cjk' },
  { char: '\u3046', name: 'U (Hiragana)', code: 'U+3046', category: 'cjk' },
  { char: '\u3048', name: 'E (Hiragana)', code: 'U+3048', category: 'cjk' },
  { char: '\u304A', name: 'O (Hiragana)', code: 'U+304A', category: 'cjk' },
  { char: '\u304B', name: 'Ka (Hiragana)', code: 'U+304B', category: 'cjk' },
  { char: '\u304D', name: 'Ki (Hiragana)', code: 'U+304D', category: 'cjk' },
  { char: '\u304F', name: 'Ku (Hiragana)', code: 'U+304F', category: 'cjk' },
  { char: '\u3051', name: 'Ke (Hiragana)', code: 'U+3051', category: 'cjk' },
  { char: '\u3053', name: 'Ko (Hiragana)', code: 'U+3053', category: 'cjk' },
  { char: '\u3055', name: 'Sa (Hiragana)', code: 'U+3055', category: 'cjk' },
  { char: '\u3057', name: 'Shi (Hiragana)', code: 'U+3057', category: 'cjk' },
  { char: '\u3059', name: 'Su (Hiragana)', code: 'U+3059', category: 'cjk' },
  { char: '\u305B', name: 'Se (Hiragana)', code: 'U+305B', category: 'cjk' },
  { char: '\u305D', name: 'So (Hiragana)', code: 'U+305D', category: 'cjk' },
  { char: '\u305F', name: 'Ta (Hiragana)', code: 'U+305F', category: 'cjk' },
  { char: '\u3061', name: 'Chi (Hiragana)', code: 'U+3061', category: 'cjk' },
  { char: '\u3064', name: 'Tsu (Hiragana)', code: 'U+3064', category: 'cjk' },
  { char: '\u3066', name: 'Te (Hiragana)', code: 'U+3066', category: 'cjk' },
  { char: '\u3068', name: 'To (Hiragana)', code: 'U+3068', category: 'cjk' },
  { char: '\u306A', name: 'Na (Hiragana)', code: 'U+306A', category: 'cjk' },
  { char: '\u306B', name: 'Ni (Hiragana)', code: 'U+306B', category: 'cjk' },
  { char: '\u306C', name: 'Nu (Hiragana)', code: 'U+306C', category: 'cjk' },
  { char: '\u306D', name: 'Ne (Hiragana)', code: 'U+306D', category: 'cjk' },
  { char: '\u306E', name: 'No (Hiragana)', code: 'U+306E', category: 'cjk' },
  { char: '\u306F', name: 'Ha (Hiragana)', code: 'U+306F', category: 'cjk' },
  { char: '\u3072', name: 'Hi (Hiragana)', code: 'U+3072', category: 'cjk' },
  { char: '\u3075', name: 'Fu (Hiragana)', code: 'U+3075', category: 'cjk' },
  { char: '\u3078', name: 'He (Hiragana)', code: 'U+3078', category: 'cjk' },
  { char: '\u307B', name: 'Ho (Hiragana)', code: 'U+307B', category: 'cjk' },
  { char: '\u307E', name: 'Ma (Hiragana)', code: 'U+307E', category: 'cjk' },
  { char: '\u307F', name: 'Mi (Hiragana)', code: 'U+307F', category: 'cjk' },
  { char: '\u3080', name: 'Mu (Hiragana)', code: 'U+3080', category: 'cjk' },
  { char: '\u3081', name: 'Me (Hiragana)', code: 'U+3081', category: 'cjk' },
  { char: '\u3082', name: 'Mo (Hiragana)', code: 'U+3082', category: 'cjk' },
  { char: '\u3084', name: 'Ya (Hiragana)', code: 'U+3084', category: 'cjk' },
  { char: '\u3086', name: 'Yu (Hiragana)', code: 'U+3086', category: 'cjk' },
  { char: '\u3088', name: 'Yo (Hiragana)', code: 'U+3088', category: 'cjk' },
  { char: '\u3089', name: 'Ra (Hiragana)', code: 'U+3089', category: 'cjk' },
  { char: '\u308A', name: 'Ri (Hiragana)', code: 'U+308A', category: 'cjk' },
  { char: '\u308B', name: 'Ru (Hiragana)', code: 'U+308B', category: 'cjk' },
  { char: '\u308C', name: 'Re (Hiragana)', code: 'U+308C', category: 'cjk' },
  { char: '\u308D', name: 'Ro (Hiragana)', code: 'U+308D', category: 'cjk' },
  { char: '\u308F', name: 'Wa (Hiragana)', code: 'U+308F', category: 'cjk' },
  { char: '\u3092', name: 'Wo (Hiragana)', code: 'U+3092', category: 'cjk' },
  { char: '\u3093', name: 'N (Hiragana)', code: 'U+3093', category: 'cjk' },
  { char: '\u30A2', name: 'A (Katakana)', code: 'U+30A2', category: 'cjk' },
  { char: '\u30A4', name: 'I (Katakana)', code: 'U+30A4', category: 'cjk' },
  { char: '\u30A6', name: 'U (Katakana)', code: 'U+30A6', category: 'cjk' },
  { char: '\u30A8', name: 'E (Katakana)', code: 'U+30A8', category: 'cjk' },
  { char: '\u30AA', name: 'O (Katakana)', code: 'U+30AA', category: 'cjk' },
  { char: '\u30AB', name: 'Ka (Katakana)', code: 'U+30AB', category: 'cjk' },
  { char: '\u30AD', name: 'Ki (Katakana)', code: 'U+30AD', category: 'cjk' },
  { char: '\u30AF', name: 'Ku (Katakana)', code: 'U+30AF', category: 'cjk' },
  { char: '\u30B1', name: 'Ke (Katakana)', code: 'U+30B1', category: 'cjk' },
  { char: '\u30B3', name: 'Ko (Katakana)', code: 'U+30B3', category: 'cjk' },
  { char: '\u30B5', name: 'Sa (Katakana)', code: 'U+30B5', category: 'cjk' },
  { char: '\u30B7', name: 'Shi (Katakana)', code: 'U+30B7', category: 'cjk' },
  { char: '\u30B9', name: 'Su (Katakana)', code: 'U+30B9', category: 'cjk' },
  { char: '\u30BB', name: 'Se (Katakana)', code: 'U+30BB', category: 'cjk' },
  { char: '\u30BD', name: 'So (Katakana)', code: 'U+30BD', category: 'cjk' },
  { char: '\u30BF', name: 'Ta (Katakana)', code: 'U+30BF', category: 'cjk' },
  { char: '\u30C1', name: 'Chi (Katakana)', code: 'U+30C1', category: 'cjk' },
  { char: '\u30C4', name: 'Tsu (Katakana)', code: 'U+30C4', category: 'cjk' },
  { char: '\u30C6', name: 'Te (Katakana)', code: 'U+30C6', category: 'cjk' },
  { char: '\u30C8', name: 'To (Katakana)', code: 'U+30C8', category: 'cjk' },
  { char: '\u30CA', name: 'Na (Katakana)', code: 'U+30CA', category: 'cjk' },
  { char: '\u30CB', name: 'Ni (Katakana)', code: 'U+30CB', category: 'cjk' },
  { char: '\u30CC', name: 'Nu (Katakana)', code: 'U+30CC', category: 'cjk' },
  { char: '\u30CD', name: 'Ne (Katakana)', code: 'U+30CD', category: 'cjk' },
  { char: '\u30CE', name: 'No (Katakana)', code: 'U+30CE', category: 'cjk' },
  { char: '\u30CF', name: 'Ha (Katakana)', code: 'U+30CF', category: 'cjk' },
  { char: '\u30D2', name: 'Hi (Katakana)', code: 'U+30D2', category: 'cjk' },
  { char: '\u30D5', name: 'Fu (Katakana)', code: 'U+30D5', category: 'cjk' },
  { char: '\u30D8', name: 'He (Katakana)', code: 'U+30D8', category: 'cjk' },
  { char: '\u30DB', name: 'Ho (Katakana)', code: 'U+30DB', category: 'cjk' },
  { char: '\u30DE', name: 'Ma (Katakana)', code: 'U+30DE', category: 'cjk' },
  { char: '\u30DF', name: 'Mi (Katakana)', code: 'U+30DF', category: 'cjk' },
  { char: '\u30E0', name: 'Mu (Katakana)', code: 'U+30E0', category: 'cjk' },
  { char: '\u30E1', name: 'Me (Katakana)', code: 'U+30E1', category: 'cjk' },
  { char: '\u30E2', name: 'Mo (Katakana)', code: 'U+30E2', category: 'cjk' },
  { char: '\u30E4', name: 'Ya (Katakana)', code: 'U+30E4', category: 'cjk' },
  { char: '\u30E6', name: 'Yu (Katakana)', code: 'U+30E6', category: 'cjk' },
  { char: '\u30E8', name: 'Yo (Katakana)', code: 'U+30E8', category: 'cjk' },
  { char: '\u30E9', name: 'Ra (Katakana)', code: 'U+30E9', category: 'cjk' },
  { char: '\u30EA', name: 'Ri (Katakana)', code: 'U+30EA', category: 'cjk' },
  { char: '\u30EB', name: 'Ru (Katakana)', code: 'U+30EB', category: 'cjk' },
  { char: '\u30EC', name: 'Re (Katakana)', code: 'U+30EC', category: 'cjk' },
  { char: '\u30ED', name: 'Ro (Katakana)', code: 'U+30ED', category: 'cjk' },
  { char: '\u30EF', name: 'Wa (Katakana)', code: 'U+30EF', category: 'cjk' },
  { char: '\u30F3', name: 'N (Katakana)', code: 'U+30F3', category: 'cjk' },
  { char: '\uFF01', name: 'Fullwidth Exclamation', code: 'U+FF01', category: 'cjk' },
  { char: '\uFF1F', name: 'Fullwidth Question', code: 'U+FF1F', category: 'cjk' },
  { char: '\uFF5E', name: 'Fullwidth Tilde', code: 'U+FF5E', category: 'cjk' },
]

const ALL3: UnicodeChar[] = [
  { char: '\u0905', name: 'A', code: 'U+0905', category: 'devanagari' },
  { char: '\u0906', name: 'Aa', code: 'U+0906', category: 'devanagari' },
  { char: '\u0907', name: 'I', code: 'U+0907', category: 'devanagari' },
  { char: '\u0909', name: 'U', code: 'U+0909', category: 'devanagari' },
  { char: '\u090F', name: 'E', code: 'U+090F', category: 'devanagari' },
  { char: '\u0915', name: 'Ka', code: 'U+0915', category: 'devanagari' },
  { char: '\u0916', name: 'Kha', code: 'U+0916', category: 'devanagari' },
  { char: '\u0917', name: 'Ga', code: 'U+0917', category: 'devanagari' },
  { char: '\u0918', name: 'Gha', code: 'U+0918', category: 'devanagari' },
  { char: '\u0919', name: 'Nga', code: 'U+0919', category: 'devanagari' },
  { char: '\u091A', name: 'Ca', code: 'U+091A', category: 'devanagari' },
  { char: '\u091B', name: 'Cha', code: 'U+091B', category: 'devanagari' },
  { char: '\u091C', name: 'Ja', code: 'U+091C', category: 'devanagari' },
  { char: '\u091D', name: 'Jha', code: 'U+091D', category: 'devanagari' },
  { char: '\u091E', name: 'Nya', code: 'U+091E', category: 'devanagari' },
  { char: '\u091F', name: 'Tta', code: 'U+091F', category: 'devanagari' },
  { char: '\u0920', name: 'Ttha', code: 'U+0920', category: 'devanagari' },
  { char: '\u0921', name: 'Dda', code: 'U+0921', category: 'devanagari' },
  { char: '\u0922', name: 'Ddha', code: 'U+0922', category: 'devanagari' },
  { char: '\u0923', name: 'Nna', code: 'U+0923', category: 'devanagari' },
  { char: '\u0924', name: 'Ta', code: 'U+0924', category: 'devanagari' },
  { char: '\u0925', name: 'Tha', code: 'U+0925', category: 'devanagari' },
  { char: '\u0926', name: 'Da', code: 'U+0926', category: 'devanagari' },
  { char: '\u0927', name: 'Dha', code: 'U+0927', category: 'devanagari' },
  { char: '\u0928', name: 'Na', code: 'U+0928', category: 'devanagari' },
  { char: '\u092A', name: 'Pa', code: 'U+092A', category: 'devanagari' },
  { char: '\u092B', name: 'Pha', code: 'U+092B', category: 'devanagari' },
  { char: '\u092C', name: 'Ba', code: 'U+092C', category: 'devanagari' },
  { char: '\u092D', name: 'Bha', code: 'U+092D', category: 'devanagari' },
  { char: '\u092E', name: 'Ma', code: 'U+092E', category: 'devanagari' },
  { char: '\u092F', name: 'Ya', code: 'U+092F', category: 'devanagari' },
  { char: '\u0930', name: 'Ra', code: 'U+0930', category: 'devanagari' },
  { char: '\u0932', name: 'La', code: 'U+0932', category: 'devanagari' },
  { char: '\u0933', name: 'Lla', code: 'U+0933', category: 'devanagari' },
  { char: '\u0935', name: 'Va', code: 'U+0935', category: 'devanagari' },
  { char: '\u0936', name: 'Sha', code: 'U+0936', category: 'devanagari' },
  { char: '\u0937', name: 'Ssa', code: 'U+0937', category: 'devanagari' },
  { char: '\u0938', name: 'Sa', code: 'U+0938', category: 'devanagari' },
  { char: '\u0939', name: 'Ha', code: 'U+0939', category: 'devanagari' },
  { char: '\u0966', name: '0', code: 'U+0966', category: 'devanagari' },
  { char: '\u0967', name: '1', code: 'U+0967', category: 'devanagari' },
  { char: '\u0968', name: '2', code: 'U+0968', category: 'devanagari' },
  { char: '\u0969', name: '3', code: 'U+0969', category: 'devanagari' },
  { char: '\u096A', name: '4', code: 'U+096A', category: 'devanagari' },
  { char: '\u096B', name: '5', code: 'U+096B', category: 'devanagari' },
  { char: '\u096C', name: '6', code: 'U+096C', category: 'devanagari' },
  { char: '\u096D', name: '7', code: 'U+096D', category: 'devanagari' },
  { char: '\u096E', name: '8', code: 'U+096E', category: 'devanagari' },
  { char: '\u096F', name: '9', code: 'U+096F', category: 'devanagari' },
  { char: '\u05D0', name: 'Alef', code: 'U+05D0', category: 'hebrew' },
  { char: '\u05D1', name: 'Bet', code: 'U+05D1', category: 'hebrew' },
  { char: '\u05D2', name: 'Gimel', code: 'U+05D2', category: 'hebrew' },
  { char: '\u05D3', name: 'Dalet', code: 'U+05D3', category: 'hebrew' },
  { char: '\u05D4', name: 'He', code: 'U+05D4', category: 'hebrew' },
  { char: '\u05D5', name: 'Vav', code: 'U+05D5', category: 'hebrew' },
  { char: '\u05D6', name: 'Zayin', code: 'U+05D6', category: 'hebrew' },
  { char: '\u05D7', name: 'Het', code: 'U+05D7', category: 'hebrew' },
  { char: '\u05D8', name: 'Tet', code: 'U+05D8', category: 'hebrew' },
  { char: '\u05D9', name: 'Yod', code: 'U+05D9', category: 'hebrew' },
  { char: '\u05DA', name: 'Final Kaf', code: 'U+05DA', category: 'hebrew' },
  { char: '\u05DB', name: 'Kaf', code: 'U+05DB', category: 'hebrew' },
  { char: '\u05DC', name: 'Lamed', code: 'U+05DC', category: 'hebrew' },
  { char: '\u05DD', name: 'Final Mem', code: 'U+05DD', category: 'hebrew' },
  { char: '\u05DE', name: 'Mem', code: 'U+05DE', category: 'hebrew' },
  { char: '\u05DF', name: 'Final Nun', code: 'U+05DF', category: 'hebrew' },
  { char: '\u05E0', name: 'Nun', code: 'U+05E0', category: 'hebrew' },
  { char: '\u05E1', name: 'Samekh', code: 'U+05E1', category: 'hebrew' },
  { char: '\u05E2', name: 'Ayin', code: 'U+05E2', category: 'hebrew' },
  { char: '\u05E3', name: 'Final Pe', code: 'U+05E3', category: 'hebrew' },
  { char: '\u05E4', name: 'Pe', code: 'U+05E4', category: 'hebrew' },
  { char: '\u05E5', name: 'Final Tsadi', code: 'U+05E5', category: 'hebrew' },
  { char: '\u05E6', name: 'Tsadi', code: 'U+05E6', category: 'hebrew' },
  { char: '\u05E7', name: 'Qof', code: 'U+05E7', category: 'hebrew' },
  { char: '\u05E8', name: 'Resh', code: 'U+05E8', category: 'hebrew' },
  { char: '\u05E9', name: 'Shin', code: 'U+05E9', category: 'hebrew' },
  { char: '\u05EA', name: 'Tav', code: 'U+05EA', category: 'hebrew' },
  { char: '\u2318', name: 'Command (Place of Interest)', code: 'U+2318', category: 'technical' },
  { char: '\u2325', name: 'Option Key', code: 'U+2325', category: 'technical' },
  { char: '\u2326', name: 'Delete Right', code: 'U+2326', category: 'technical' },
  { char: '\u232B', name: 'Delete Left (Backspace)', code: 'U+232B', category: 'technical' },
  { char: '\u2386', name: 'Enter Key', code: 'U+2386', category: 'technical' },
  { char: '\u2387', name: 'Alternative Key Symbol', code: 'U+2387', category: 'technical' },
  { char: '\u2388', name: 'Helm Symbol', code: 'U+2388', category: 'technical' },
  { char: '\u23CE', name: 'Return Symbol', code: 'U+23CE', category: 'technical' },
  { char: '\u23CF', name: 'Eject Symbol', code: 'U+23CF', category: 'technical' },
  { char: '\u23E9', name: 'Fast Forward', code: 'U+23E9', category: 'technical' },
  { char: '\u23EA', name: 'Rewind', code: 'U+23EA', category: 'technical' },
  { char: '\u23EB', name: 'Skip Up', code: 'U+23EB', category: 'technical' },
  { char: '\u23EC', name: 'Skip Down', code: 'U+23EC', category: 'technical' },
  { char: '\u23F0', name: 'Alarm Clock', code: 'U+23F0', category: 'technical' },
  { char: '\u23F3', name: 'Hourglass', code: 'U+23F3', category: 'technical' },
  { char: '\u23F8', name: 'Pause', code: 'U+23F8', category: 'technical' },
  { char: '\u23F9', name: 'Stop', code: 'U+23F9', category: 'technical' },
  { char: '\u23FA', name: 'Record', code: 'U+23FA', category: 'technical' },
  { char: '\u2600', name: 'Sun', code: 'U+2600', category: 'technical' },
  { char: '\u2601', name: 'Cloud', code: 'U+2601', category: 'technical' },
  { char: '\u2602', name: 'Umbrella', code: 'U+2602', category: 'technical' },
  { char: '\u2603', name: 'Snowman', code: 'U+2603', category: 'technical' },
  { char: '\u260E', name: 'Telephone', code: 'U+260E', category: 'technical' },
  { char: '\u2615', name: 'Hot Beverage', code: 'U+2615', category: 'technical' },
  { char: '\u2640', name: 'Female', code: 'U+2640', category: 'technical' },
  { char: '\u2642', name: 'Male', code: 'U+2642', category: 'technical' },
  { char: '\u2650', name: 'Cancer', code: 'U+2650', category: 'technical' },
  { char: '\u2651', name: 'Leo', code: 'U+2651', category: 'technical' },
  { char: '\u2652', name: 'Virgo', code: 'U+2652', category: 'technical' },
  { char: '\u2653', name: 'Libra', code: 'U+2653', category: 'technical' },
  { char: '\u2654', name: 'Scorpius', code: 'U+2654', category: 'technical' },
  { char: '\u2655', name: 'Sagittarius', code: 'U+2655', category: 'technical' },
  { char: '\u2656', name: 'Capricorn', code: 'U+2656', category: 'technical' },
  { char: '\u2657', name: 'Aquarius', code: 'U+2657', category: 'technical' },
  { char: '\u2658', name: 'Pisces', code: 'U+2658', category: 'technical' },
  { char: '\u2659', name: 'Aries', code: 'U+2659', category: 'technical' },
  { char: '\u265A', name: 'Taurus', code: 'U+265A', category: 'technical' },
  { char: '\u265B', name: 'Gemini', code: 'U+265B', category: 'technical' },
  { char: '\u265C', name: 'Cancer (alt)', code: 'U+265C', category: 'technical' },
  { char: '\u265D', name: 'Leo (alt)', code: 'U+265D', category: 'technical' },
  { char: '\u265E', name: 'Virgo (alt)', code: 'U+265E', category: 'technical' },
  { char: '\u265F', name: 'Libra (alt)', code: 'U+265F', category: 'technical' },
  { char: '\u2660', name: 'Spade', code: 'U+2660', category: 'technical' },
  { char: '\u2663', name: 'Club', code: 'U+2663', category: 'technical' },
  { char: '\u2665', name: 'Heart', code: 'U+2665', category: 'technical' },
  { char: '\u2666', name: 'Diamond', code: 'U+2666', category: 'technical' },
  { char: '\u26A0', name: 'Warning Sign', code: 'U+26A0', category: 'technical' },
  { char: '\u26A1', name: 'High Voltage', code: 'U+26A1', category: 'technical' },
  { char: '\u2611', name: 'Ballot Box with Check', code: 'U+2611', category: 'technical' },
  { char: '\u2612', name: 'Ballot Box with X', code: 'U+2612', category: 'technical' },
  { char: '\u262F', name: 'Yin Yang', code: 'U+262F', category: 'technical' },
  { char: '\u2639', name: 'White Frowning Face', code: 'U+2639', category: 'technical' },
  { char: '\u263A', name: 'White Smiling Face', code: 'U+263A', category: 'technical' },
  { char: '\u263B', name: 'Black Smiling Face', code: 'U+263B', category: 'technical' },
  { char: '\u266A', name: 'Eighth Note', code: 'U+266A', category: 'technical' },
  { char: '\u26BD', name: 'Soccer Ball', code: 'U+26BD', category: 'emoji' },
  { char: '\u26BE', name: 'Baseball', code: 'U+26BE', category: 'emoji' },
  { char: '\u26C4', name: 'Snowman', code: 'U+26C4', category: 'emoji' },
  { char: '\u26C5', name: 'Sun Behind Cloud', code: 'U+26C5', category: 'emoji' },
  { char: '\u26EA', name: 'Church', code: 'U+26EA', category: 'emoji' },
  { char: '\u26F2', name: 'Fountain', code: 'U+26F2', category: 'emoji' },
  { char: '\u26F3', name: 'Flag in Hole', code: 'U+26F3', category: 'emoji' },
  { char: '\u26F5', name: 'Sailboat', code: 'U+26F5', category: 'emoji' },
  { char: '\u26FA', name: 'Tent', code: 'U+26FA', category: 'emoji' },
  { char: '\u26FD', name: 'Fuel Pump', code: 'U+26FD', category: 'emoji' },
  { char: '\u2702', name: 'Scissors', code: 'U+2702', category: 'emoji' },
  { char: '\u2705', name: 'Check Mark Button', code: 'U+2705', category: 'emoji' },
  { char: '\u2708', name: 'Airplane', code: 'U+2708', category: 'emoji' },
  { char: '\u2709', name: 'Envelope', code: 'U+2709', category: 'emoji' },
  { char: '\u270A', name: 'Raised Fist', code: 'U+270A', category: 'emoji' },
  { char: '\u270B', name: 'Raised Hand', code: 'U+270B', category: 'emoji' },
  { char: '\u270C', name: 'Victory Hand', code: 'U+270C', category: 'emoji' },
  { char: '\u270F', name: 'Pencil', code: 'U+270F', category: 'emoji' },
  { char: '\u2712', name: 'Black Nib', code: 'U+2712', category: 'emoji' },
  { char: '\u2714', name: 'Check Mark', code: 'U+2714', category: 'emoji' },
  { char: '\u2716', name: 'Heavy Multiplication X', code: 'U+2716', category: 'emoji' },
  { char: '\u271D', name: 'Latin Cross', code: 'U+271D', category: 'emoji' },
  { char: '\u2728', name: 'Sparkles', code: 'U+2728', category: 'emoji' },
  { char: '\u272A', name: 'Star of David', code: 'U+272A', category: 'emoji' },
  { char: '\u2733', name: 'Eight Spoked Asterisk', code: 'U+2733', category: 'emoji' },
  { char: '\u2734', name: 'Eight Pointed Star', code: 'U+2734', category: 'emoji' },
  { char: '\u2744', name: 'Snowflake', code: 'U+2744', category: 'emoji' },
  { char: '\u2747', name: 'Sparkle', code: 'U+2747', category: 'emoji' },
  { char: '\u274C', name: 'Cross Mark', code: 'U+274C', category: 'emoji' },
  { char: '\u274E', name: 'Cross Mark Button', code: 'U+274E', category: 'emoji' },
  { char: '\u2753', name: 'Question Mark', code: 'U+2753', category: 'emoji' },
  { char: '\u2754', name: 'White Question Mark', code: 'U+2754', category: 'emoji' },
  { char: '\u2755', name: 'White Exclamation Mark', code: 'U+2755', category: 'emoji' },
  { char: '\u2757', name: 'Exclamation Mark', code: 'U+2757', category: 'emoji' },
  { char: '\u2763', name: 'Heart Exclamation', code: 'U+2763', category: 'emoji' },
  { char: '\u2764', name: 'Red Heart', code: 'U+2764', category: 'emoji' },
  { char: '\u2795', name: 'Plus', code: 'U+2795', category: 'emoji' },
  { char: '\u2796', name: 'Minus', code: 'U+2796', category: 'emoji' },
  { char: '\u2797', name: 'Division', code: 'U+2797', category: 'emoji' },
  { char: '\u27A1', name: 'Right Arrow', code: 'U+27A1', category: 'emoji' },
  { char: '\u27B0', name: 'Curly Loop', code: 'U+27B0', category: 'emoji' },
  { char: '\u27BF', name: 'Double Curly Loop', code: 'U+27BF', category: 'emoji' },
  { char: '\u2934', name: 'Up Right Arrow', code: 'U+2934', category: 'emoji' },
  { char: '\u2935', name: 'Down Right Arrow', code: 'U+2935', category: 'emoji' },
  { char: '\u2B05', name: 'Left Arrow', code: 'U+2B05', category: 'emoji' },
  { char: '\u2B06', name: 'Up Arrow', code: 'U+2B06', category: 'emoji' },
  { char: '\u2B07', name: 'Down Arrow', code: 'U+2B07', category: 'emoji' },
  { char: '\u2B1B', name: 'Black Square', code: 'U+2B1B', category: 'emoji' },
  { char: '\u2B1C', name: 'White Square', code: 'U+2B1C', category: 'emoji' },
  { char: '\u2B50', name: 'Star', code: 'U+2B50', category: 'emoji' },
  { char: '\u2B55', name: 'Heavy Circle', code: 'U+2B55', category: 'emoji' },
  { char: '\u3030', name: 'Wavy Dash', code: 'U+3030', category: 'emoji' },
  { char: '\u303D', name: 'Part Alternation Mark', code: 'U+303D', category: 'emoji' },
  { char: '\u3297', name: 'Congratulations', code: 'U+3297', category: 'emoji' },
  { char: '\u3299', name: 'Secret', code: 'U+3299', category: 'emoji' },
]

export const ALL_CHARS: UnicodeChar[] = [...ALL, ...ALL2, ...ALL3]

export function getCharsByCategory(category: string): UnicodeChar[] {
  return ALL_CHARS.filter(c => c.category === category)
}

export function searchChars(query: string): UnicodeChar[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return ALL_CHARS.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.char.includes(q) ||
    c.code.toLowerCase().includes(q)
  ).slice(0, 100)
}
